adjective = "abrupt"
adjective1 = "warm"
bird = "chicken"
room = "kitchen"
verb = "ran"
verb1 = "set"
name = "Jacob"
noun = "drink"
liquid = "milk" 
verbing = "living"
print("It was a " + adjective + ", cold November day. I woke up to the " + adjective1 + " smell of " + bird + " roasting in the " + room + " downstairs. I " + verb + " down the stairs to see if I could help " + verb1 + " the dinner. My mom said, see if " + name + " needs a fresh " + noun + ". So I carried a tray of glasses full of " + liquid + " into the " + verbing + " room. ")